### ISSUE TITLE
Empty Broker index

### ISSUE THREAD

**Issue by sebplorenz** [Mobility-Data-Space/mobility-data-space#12]
After restarting the broker services (due to vm server update) I'm getting the following resonse:
```
{
  "reason": {
    "properties": null,
    "@id": "https://w3id.org/idsa/code/NOT_FOUND"
  },
  "payload": "The index is empty - your query could not be evaluated.",
  "type": "de.fraunhofer.iais.eis.RejectionMessageImpl"
}
```
when querying for all connectors.
My query looks like this:
```
PREFIX ids: <https://w3id.org/idsa/core/>
            SELECT ?url WHERE { ?x a ids:ConnectorEndpoint .
            ?x ids:accessURL ?url }
```
Environment: Test

It seems like some indexes do not survive a restart. While others do.

**Comment by sebplorenz** [comment]
Also in the Broker web frontend all connectors are gone, whilst the resources are still there. Maybe this has something to do with the reindexing over night.

**Comment by sebbader** [comment]
Hi @sebplorenz, we are on this. Now it should be working fine for new requests at least.

**Comment by ip312** [comment]
Not relevant anymore.
