### ISSUE TITLE
Extension of the string length for the Connector Description up to 1000 characters

### ISSUE THREAD

**Issue by ip312** [Mobility-Data-Space/mobility-data-space#21]
Currently the string length for connector descriptions is restricted to 255 characters.
The string length of the connector description in at least one Use Case, which is already implemented, is 336 characters.
Currently there is no possibility to publish this description. 
I would suggest to extend the string length for this field up to at least 1000 characters.

**Comment by edgardmarx** [comment]
There is an open ticket in the IDS Connector regarding this issue: https://github.com/International-Data-Spaces-Association/DataspaceConnector/issues/619

**Comment by sebplorenz** [comment]
Hi, it is confirmed that this is a connector issue. The connector developers will take care of this.
