### ISSUE TITLE
Duplicated element sub:FuelPrice

### ISSUE THREAD

**Issue by SebastianOpriel** [Mobility-Data-Space/mobility-data-space#25]
sub:FuelPrice is defined twice, see
https://github.com/Mobility-Data-Space/mobility-data-space/blob/40d1af61951edbe6c95736b4c7bbfdf919e46ea4/ontology/MDS-Ontology.ttl#L212

We shall agree on just one definition.

**Comment by ip312** [comment]
Copypasre error fixed
https://github.com/Mobility-Data-Space/mobility-data-space/commit/cc4f6cba06f3431aca81347e16f83c806278842a
