### ISSUE TITLE
Negotiation for Test-Catalog offer doesn't load

### ISSUE THREAD

**Issue by smartin314** [Mobility-Data-Space/mobility-data-space#33]
I have a MDS EDC Connector running on a Server gaiax.example.de that is configured with traefik and follows this template: https://github.com/Mobility-Data-Space/mobility-data-space/blob/main/templates/connector_with_traefik.yaml 
Because it's still a test phase the Server is only reachable in my Intranet. But the DSP-Callback address (gaiax.example.de/api/dsp) is reachable in the Internet via a Proxy from apps.example.de/api/dsp. The Dashboard also runs in the Intranet.

The Dashboard and the Test-Catalog: https://mds-test-next-001.prod-sovity.azure.sovity.io/api/dsp load with no problem. I can also configure a Dataoffer and don't get any errors. But in the MDS-Portal I don't see it.

Also when I want to access a data offer from the test catalog and negotiate it, I end in a endless loading loop. The negotiating just doesn't finish. In the network-analyse tool I saw that the Dashboard is sending the whole time requests to the Management-API but only receives this response: `{"contractNegotiationId":"d4f526bd-d9fb-42b3-8dc5-75abfb6ba6e6","createdAt":"2024-10-24T06:55:58.888Z","contractAgreementId":null,"state":{"name":"REQUESTED","code":200,"simplifiedState":"IN_PROGRESS"}}`

My question is now, how does the Negotiation-process work. How should my server be reachable and from where. Is the problem the Proxy and that direct access from the Internet to gaiax.example.de/api/dsp is not possible?

**Comment by DanielHeiderMDS** [comment]
Hi, could you tell us the the Connector-ID please? We can see that you tried to register multiple connectors in the portal.

**Comment by DanielHeiderMDS** [comment]
We would also like to add that this is our public github. All the information here is publicly visible.
Please use https://support.mobility-dataspace.eu/ for non-support issues.

**Comment by mstona** [comment]
> Hi, could you tell us the the Connector-ID please? We can see that you tried to register multiple connectors in the portal.

The Connector-ID is "MDSLMBSGZ2.CF101XK".

**Comment by ip312** [comment]
I deleted the comment with an MDS Id.

**Comment by ip312** [comment]
Solved
